name: esp_provisioning
description: Espressif Provisioning library
version: 1.0.0+6
homepage: https://github.com/sunshine-tech/esp_provisioning.git


environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^2.0.0
  cryptography: ^2.0.5
  collection: ^1.15.0
  flutter_blue_plus: ^1.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.tuanpm.esp_provisioning
        pluginClass: EspProvisioningPlugin
      ios:
        pluginClass: EspProvisioningPlugin
